# Site settings
title: 意星
description: "日月運行 一寒一暑"
url:  "https://www.e11520.com" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "意星"
  email: "songhx@gmail.com"
  url: "https://www.e11520.com"
permalink: /:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 10
paginate_path: "/page:num/"

#SEO
twitter:
  username: 
  card: 
facebook:
  app_id: # Facebook app ID for Facebook insights
  publisher: # Facebook page URL or ID of the publishing entity
  admins: # Facebook user ID for domain insights linked to a personal account
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: zh_CN

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never

#Collection
collections_dir: articles
collections:
  yijing:
    output: true
    permalink: /book/:collection/:path
  suwen:
    output: true
    permalink: /book/:collection/:path