#Google Analytics
analytics-id: G-7V08PJ7CTD

#Subtitle
subtitle:
  active: true
  text: 日月運行 一寒一暑

#Nav 
nav:
  pages:
    active: true
  social:
    active: true

#Featured images in homepage
featured-img:
  active: true

#Show categories at the end of posts
categories:
  active: false

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: false

#Show related posts based on categories
related-posts:
  active: false
  title: "相关文章"

#Comments
comments: false
